# Generated by Django 4.0.6 on 2022-11-03 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distirc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=244)),
            ],
        ),
        migrations.AddField(
            model_name='region',
            name='distirc',
            field=models.ManyToManyField(to='main.distirc'),
        ),
    ]
